version: '3'
services:
  web:
    build: .
    command: gunicorn My_webpage_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_webpage_db_user
      - POSTGRES_PASSWORD=my_webpage_db_password
      - POSTGRES_DB=my_webpage_dev
volumes:
  postgres_data: